---
swagger: "2.0"

info:
  description: "Image analyzer service for anchore-engine"
  version: "0.9.0"
  title: "Image Analyzer"
  contact:
    email: "dev@anchore.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

#host: "localhost:83"

basePath: "/"

tags:
- name: "analyzer"
  description: "Image Analyzer"
  externalDocs:
    description: "Find out more"
    url: "http://anchore.com"

schemes:
- "https"
- "http"

securityDefinitions:
  basicAuth:
    type: basic

security:
  - basicAuth: []

paths:
  /status:
    get:
      tags:
      - "analyzer"
      summary: "Get the status of the service"
      description: ""
      operationId: "status"
      produces:
      - "application/json"
      responses:
        200:
          description: "success"
          description: "service status"
          schema:
            type: object
      x-swagger-router-controller: "anchore_engine.services.analyzer.api.controllers.default_controller"
  /analyze:
    get:
      tags:
      - "analyzer"
      summary: "Perform DB side-effect free interactive analysis"
      description: ""
      operationId: "interactive_analyze"
      parameters:
      - name: 'bodycontent'
        in: body
        schema:
          type: object
        description: "object describing image to analyze"
        required: true
      produces:
      - "application/json"
      responses:
        200:
          description: "success"
          schema:
            type: object
      x-swagger-router-controller: "anchore_engine.services.analyzer.api.controllers.default_controller"
