FROM docker.io/library/ubuntu:18.04

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV GOPATH=/go

EXPOSE 8228 8338
RUN mkdir -p /go /config && \
    apt-get -y update && \
    apt-get -y install \
        vim \
        curl \
        psmisc \
        git \
        rpm \
        python3 \
        python3-pip \
        golang \
        btrfs-tools \
        git-core \
        libdevmapper-dev \
        libgpgme11-dev \
        go-md2man \
        libglib2.0-dev \
        libostree-dev && \
    git clone https://github.com/containers/skopeo $GOPATH/src/github.com/containers/skopeo && \
    cd $GOPATH/src/github.com/containers/skopeo && \
    make binary-local && \
    make install

COPY anchore-engine/ /root/anchore-engine
COPY engine-cli/ /root/anchore-engine-cli

RUN cd /root/anchore-engine/ && pip3 install --upgrade . && rm -rf .git
RUN cd /root/engine-cli/ && pip3 install --upgrade . && rm -rf .git

CMD anchore-engine
