# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from anchore_engine.services.policy_engine.api.models.base_model_ import Model
from anchore_engine.services.policy_engine.api import util


class FeedUpdateNotification(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, event_timestamp=None, feed_name=None, feed_group=None, data=None):  # noqa: E501
        """FeedUpdateNotification - a model defined in Swagger

        :param event_timestamp: The event_timestamp of this FeedUpdateNotification.  # noqa: E501
        :type event_timestamp: datetime
        :param feed_name: The feed_name of this FeedUpdateNotification.  # noqa: E501
        :type feed_name: str
        :param feed_group: The feed_group of this FeedUpdateNotification.  # noqa: E501
        :type feed_group: str
        :param data: The data of this FeedUpdateNotification.  # noqa: E501
        :type data: List[object]
        """
        self.swagger_types = {
            'event_timestamp': datetime,
            'feed_name': str,
            'feed_group': str,
            'data': List[object]
        }

        self.attribute_map = {
            'event_timestamp': 'event_timestamp',
            'feed_name': 'feed_name',
            'feed_group': 'feed_group',
            'data': 'data'
        }

        self._event_timestamp = event_timestamp
        self._feed_name = feed_name
        self._feed_group = feed_group
        self._data = data

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FeedUpdateNotification of this FeedUpdateNotification.  # noqa: E501
        :rtype: FeedUpdateNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def event_timestamp(self):
        """Gets the event_timestamp of this FeedUpdateNotification.

        The time of the external event. Should be set to when the event occurred, to the delivery time  # noqa: E501

        :return: The event_timestamp of this FeedUpdateNotification.
        :rtype: datetime
        """
        return self._event_timestamp

    @event_timestamp.setter
    def event_timestamp(self, event_timestamp):
        """Sets the event_timestamp of this FeedUpdateNotification.

        The time of the external event. Should be set to when the event occurred, to the delivery time  # noqa: E501

        :param event_timestamp: The event_timestamp of this FeedUpdateNotification.
        :type event_timestamp: datetime
        """

        self._event_timestamp = event_timestamp

    @property
    def feed_name(self):
        """Gets the feed_name of this FeedUpdateNotification.


        :return: The feed_name of this FeedUpdateNotification.
        :rtype: str
        """
        return self._feed_name

    @feed_name.setter
    def feed_name(self, feed_name):
        """Sets the feed_name of this FeedUpdateNotification.


        :param feed_name: The feed_name of this FeedUpdateNotification.
        :type feed_name: str
        """

        self._feed_name = feed_name

    @property
    def feed_group(self):
        """Gets the feed_group of this FeedUpdateNotification.


        :return: The feed_group of this FeedUpdateNotification.
        :rtype: str
        """
        return self._feed_group

    @feed_group.setter
    def feed_group(self, feed_group):
        """Sets the feed_group of this FeedUpdateNotification.


        :param feed_group: The feed_group of this FeedUpdateNotification.
        :type feed_group: str
        """

        self._feed_group = feed_group

    @property
    def data(self):
        """Gets the data of this FeedUpdateNotification.


        :return: The data of this FeedUpdateNotification.
        :rtype: List[object]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this FeedUpdateNotification.


        :param data: The data of this FeedUpdateNotification.
        :type data: List[object]
        """

        self._data = data
