# coding: utf-8


from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from anchore_engine.services.policy_engine.api.models.base_model_ import Model
from anchore_engine.services.policy_engine.api import util


class FeedSyncTask(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, force_flush=None):  # noqa: E501
        """FeedSyncTask - a model defined in Swagger

        :param force_flush: The force_flush of this FeedSyncTask.  # noqa: E501
        :type force_flush: bool
        """
        self.swagger_types = {
            'force_flush': bool
        }

        self.attribute_map = {
            'force_flush': 'force_flush'
        }

        self._force_flush = force_flush

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FeedSyncTask of this FeedSyncTask.  # noqa: E501
        :rtype: FeedSyncTask
        """
        return util.deserialize_model(dikt, cls)

    @property
    def force_flush(self):
        """Gets the force_flush of this FeedSyncTask.

        If set, the sync will remove all local feed data and perform a full update of all data from the source  # noqa: E501

        :return: The force_flush of this FeedSyncTask.
        :rtype: bool
        """
        return self._force_flush

    @force_flush.setter
    def force_flush(self, force_flush):
        """Sets the force_flush of this FeedSyncTask.

        If set, the sync will remove all local feed data and perform a full update of all data from the source  # noqa: E501

        :param force_flush: The force_flush of this FeedSyncTask.
        :type force_flush: bool
        """

        self._force_flush = force_flush
