# coding: utf-8

from __future__ import absolute_import
from .trigger_spec import TriggerSpec
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class GateSpec(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, description=None, triggers=None):
        """
        GateSpec - a model defined in Swagger

        :param name: The name of this GateSpec.
        :type name: str
        :param description: The description of this GateSpec.
        :type description: str
        :param triggers: The triggers of this GateSpec.
        :type triggers: List[TriggerSpec]
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'triggers': List[TriggerSpec]
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'triggers': 'triggers'
        }

        self._name = name
        self._description = description
        self._triggers = triggers

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GateSpec of this GateSpec.
        :rtype: GateSpec
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self):
        """
        Gets the name of this GateSpec.
        Gate name, as it would appear in a policy document

        :return: The name of this GateSpec.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this GateSpec.
        Gate name, as it would appear in a policy document

        :param name: The name of this GateSpec.
        :type name: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this GateSpec.
        Description of the gate

        :return: The description of this GateSpec.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this GateSpec.
        Description of the gate

        :param description: The description of this GateSpec.
        :type description: str
        """

        self._description = description

    @property
    def triggers(self):
        """
        Gets the triggers of this GateSpec.
        List of the triggers that can fire for this Gate

        :return: The triggers of this GateSpec.
        :rtype: List[TriggerSpec]
        """
        return self._triggers

    @triggers.setter
    def triggers(self, triggers):
        """
        Sets the triggers of this GateSpec.
        List of the triggers that can fire for this Gate

        :param triggers: The triggers of this GateSpec.
        :type triggers: List[TriggerSpec]
        """

        self._triggers = triggers

