# coding: utf-8

from __future__ import absolute_import
from .policy_evaluation_problem import PolicyEvaluationProblem
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class PolicyValidationResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, valid=None, validation_details=None):
        """
        PolicyValidationResponse - a model defined in Swagger

        :param valid: The valid of this PolicyValidationResponse.
        :type valid: bool
        :param validation_details: The validation_details of this PolicyValidationResponse.
        :type validation_details: List[PolicyEvaluationProblem]
        """
        self.swagger_types = {
            'valid': bool,
            'validation_details': List[PolicyEvaluationProblem]
        }

        self.attribute_map = {
            'valid': 'valid',
            'validation_details': 'validation_details'
        }

        self._valid = valid
        self._validation_details = validation_details

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PolicyValidationResponse of this PolicyValidationResponse.
        :rtype: PolicyValidationResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def valid(self):
        """
        Gets the valid of this PolicyValidationResponse.
        The validation result. If True, the policy bundle is valid. If False, it is invalid and there should be content in the validation_details property.

        :return: The valid of this PolicyValidationResponse.
        :rtype: bool
        """
        return self._valid

    @valid.setter
    def valid(self, valid):
        """
        Sets the valid of this PolicyValidationResponse.
        The validation result. If True, the policy bundle is valid. If False, it is invalid and there should be content in the validation_details property.

        :param valid: The valid of this PolicyValidationResponse.
        :type valid: bool
        """

        self._valid = valid

    @property
    def validation_details(self):
        """
        Gets the validation_details of this PolicyValidationResponse.
        An array of validation details including error messages as appropriate. Will be empty on a successful validation.

        :return: The validation_details of this PolicyValidationResponse.
        :rtype: List[PolicyEvaluationProblem]
        """
        return self._validation_details

    @validation_details.setter
    def validation_details(self, validation_details):
        """
        Sets the validation_details of this PolicyValidationResponse.
        An array of validation details including error messages as appropriate. Will be empty on a successful validation.

        :param validation_details: The validation_details of this PolicyValidationResponse.
        :type validation_details: List[PolicyEvaluationProblem]
        """

        self._validation_details = validation_details

