#!/usr/bin/env bash
set -euvo pipefail

CI_COMPOSE_FILE=$1
WORKSPACE_DIR=/tmp/job-workspace

# Optional - only used for print_colorized
source anchore-ci/utils

print_colorized INFO "Running Anchore Engine functional tests."; echo

docker-compose -f ${CI_COMPOSE_FILE} exec job-runner bash -c "\
set -x && \
anchore-cli --u admin --p foobar --url http://engine-api:8228/v1 system wait --feedsready '' && \
anchore-cli --u admin --p foobar --url http://engine-api:8228/v1 system status && \
/home/anchore/.local/bin/tox tests/functional --result-json .tox/test-reports.log ;\
"

print_colorized INFO "Finished running Anchore Engine functional tests."; echo
