#!/usr/bin/env bash

set -euvo pipefail

# Only run this in CI
if [[ "${CI:-false}" == true ]]; then

    IMAGE="${1:?'Missing required parameter: IMAGE'}"
    TAG="${2:?'Missing required parameter: TAG'}"
    CONFIG_FILE="${3:?'Missing required parameter: CONFIG_FILE'}"

    source anchore-ci/utils

    ARCH=$(uname | tr '[:upper:]' '[:lower:]')

    print_colorized INFO "Installing container-structure-tests."
    curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-"${ARCH}"-amd64
    chmod +x container-structure-test-"${ARCH}"-amd64

    # If we're asking for "prod", that means ${IMAGE}:latest, which means we
    # want to pull and check that image from dockerhub
    if [[ "${TAG}" == "prod" ]]; then
      test "${DOCKER_USER:?'Missing required environment variable: DOCKER_USER'}"
      test "${DOCKER_PASS:?'Missing required environment variable: DOCKER_PASS'}"
      echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
      IMAGE="anchore/${IMAGE}"
      TAG="latest"
      docker pull "${IMAGE}:${TAG}"
    fi

    print_colorized INFO "Running container-structure-tests for ${IMAGE}:${TAG}."
    ./container-structure-test-"${ARCH}"-amd64 test --image "${IMAGE}:${TAG}" -c "${CONFIG_FILE}"

    print_colorized INFO "Finished running container-structure-tests."
fi
