name: Code Scan
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ShiftLeftSecurity/scan-action@master
        with:
          output: reports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: scan-reports
          path: reports/
